✨ feat: Created home landing page #1
italanta/elewa-website-html pull request #103
Opened 2023-09-30 13:22 UTC by Makig10

# Description
Created the home landing page to resolve issue 1
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-05 06:13 UTC, JAPHETHNYARANGA requested changes
Use lipstick emoji for ui elements. Please make the page responsive also and share screen shots.

2023-10-05 06:13 UTC, JAPHETHNYARANGA commented on index.html
> +      <img>
?? whats going on here

2023-10-05 06:21 UTC, Makig10 commented
Ok, will do that.

On Thu, 5 Oct 2023 at 09:13, Japheth Nyaranga ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Use lipstick emoji for ui elements. Please make the page responsive also
> and share screen shots.
> ------------------------------
>
> In index.html
> <https://github.com/italanta/elewa-website-html/pull/103#discussion_r1345824240>
> :
>
> > +      <img>
> +      <img>
> +      <img>
> +      <img>
> +      <img>
> +      <img>
> +      <img>
>
> ?? whats going on here
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website-html/pull/103#pullrequestreview-1657576988>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4FFFPOXIWXPPBEQ2UHRZYTX5ZFXVAVCNFSM6AAAAAA5NR5ODOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJXGU3TMOJYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-19 08:04 UTC, JAPHETHNYARANGA commented
closing as this is done, please pick another issue

2023-10-19 08:04 UTC, closed without merging

2023-10-21 10:44 UTC, Makig10 commented
Awesome, thanks for the update!

On Thu, 19 Oct 2023 at 11:04, Japheth Nyaranga ***@***.***>
wrote:

> Closed #103 <https://github.com/italanta/elewa-website-html/pull/103>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website-html/pull/103#event-10706634132>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4FFFPODMG5B6QRDQG6FQ4TYADNJFAVCNFSM6AAAAAA5NR5ODOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJQG4YDMNRTGQYTGMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>