🎨 create the home landing page #2
italanta/elewa-website-html pull request #108
Opened 2023-09-30 20:44 UTC by Schola-droid

# Description

A navigation bar with links and a contact button.
Content includes a heading, a paragraph, and a button with an arrow icon.
An image with the class "feature-image

Reference the issue related to this PR as shown below. Every issue has its own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #2, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Screenshot (optional)
<img width="1778" alt="Home-landing-page" src="https://github.com/italanta/elewa-website-html/assets/126864511/410a13dc-123f-457c-9287-85733aef752a">
@Johnson Njichi

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2023-10-03 12:18 UTC, JAPHETHNYARANGA requested changes
Is the page responsive, i cannot see specific screen sizes specified.  https://www.w3schools.com/css/css_rwd_mediaqueries.asp

2023-10-03 12:18 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-left: 200px
use single margin property here  
If the margin property has four values:

margin: 25px 50px 75px 100px;
top margin is 25px
right margin is 50px
bottom margin is 75px
left margin is 100px

2023-10-03 12:18 UTC, JAPHETHNYARANGA commented on src/ts/index.ts
> +console.log(b);
this is not necessary for the pull request

2023-10-07 10:11 UTC, Schola-droid commented
> Is the page responsive, i cannot see specific screen sizes specified. https://www.w3schools.com/css/css_rwd_mediaqueries.asp

Working on it sir

2023-10-07 10:12 UTC, Schola-droid commented on src/css/style.css
> +    margin-left: 200px
> use single margin property here If the margin property has four values:
> 
> margin: 25px 50px 75px 100px; top margin is 25px right margin is 50px bottom margin is 75px left margin is 100px

Okay

2023-10-07 10:12 UTC, Schola-droid commented on src/ts/index.ts
> +console.log(b);
> this is not necessary for the pull request

Noted sir.

2023-10-08 21:56 UTC, Schola-droid commented on src/css/style.css
> +    margin-left: 200px
Done with the revision @JAPHETHNYARANGA

2023-10-11 09:46 UTC, JAPHETHNYARANGA submitted a review, later dismissed

2023-10-11 09:53 UTC, JAPHETHNYARANGA approved these changes

2023-10-11 09:53 UTC, merged