Home page overview section #4
italanta/elewa-website-html pull request #126
Opened 2023-10-02 06:01 UTC by mumbi58

# Description
Summary of Changes:
I have built an overview page using HTML and styled it using CSS to create a visually appealing and informative web page.
Motivation: To help many people learn easily and enjoyably, Elewa uses a people-focused approach to make education and training accessible for all.

Dependencies:
There are no external dependencies for this change. It was implemented using standard HTML and CSS techniques, making it compatible with a wide range of web environments.
#4 
## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Screenshot 
large screens view
![image](https://github.com/italanta/elewa-website-html/assets/126749794/6252dd70-853a-4f45-b1d5-34691164af66)
 phone view below
![image](https://github.com/italanta/elewa-website-html/assets/126749794/f194ac39-8f92-4707-afb9-7d50a3137515)
tablet view below
![image](https://github.com/italanta/elewa-website-html/assets/126749794/d51b33bf-5e34-4b7f-ae76-8999af296989)

## How Has This Been Tested?
I used manual cross-device testing which involves manually resizing the browser window or using the browser's built-in device emulation features to simulate how your website looks and behaves on various devices such as mobile phones, tablets, and desktops.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-12 07:46 UTC, JAPHETHNYARANGA requested changes
Very good attempt, the mobile screen align alignment seems a bit off, anf the font weight, style and sizes. With these changes we'll be good to go

2023-10-12 07:46 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-top: 10%;
use shorthand

2023-10-12 07:46 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-top: 5%;
here also

2023-10-12 07:46 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-left: 10%;
here

2023-10-12 07:46 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-top: 5%;
here

2023-10-12 09:17 UTC, mumbi58 commented
i have made the changes

2023-10-12 09:17 UTC, mumbi58 commented on src/css/style.css
> +    margin-top: 5%;
i have made the changes requested

2023-10-22 19:44 UTC, JAPHETHNYARANGA commented
Good attempt but this issue has been closed . Please pick another open issue. Hint; don't delete code already in a file when working on it.

2023-10-22 19:44 UTC, closed without merging