🎨 Create Home Page News Section Component #7
italanta/elewa-website-html pull request #136
Opened 2023-10-02 10:42 UTC by mshekerotokiti

# Description

I have created the news page, with the read more links that direct to the specific blog page

Reference the issue related to this PR as shown below. Every issue has its own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # 7 
## Type of change

:white_check_mark:  New feature (non-breaking change which adds functionality)

## Screenshot (optional)

![Screenshot from 2023-10-02 13-28-16](https://github.com/italanta/elewa-website-html/assets/116310361/9cd3e27e-96c4-4393-aae1-4e40a70f446c)

## Checklist

:white_check_mark:  My code follows the style guidelines of this project
 :white_check_mark:  I have performed a self-review of my code
:white_check_mark: I have commented my code, particularly in hard-to-understand areas
  :white_check_mark: My changes generate no new warnings

2023-10-02 10:52 UTC, mshekerotokiti commented
Fixes #7

2023-10-04 09:37 UTC, JAPHETHNYARANGA requested changes
Good work, just go through your files again and  remember to attack phone size screenshot.

2023-10-04 09:37 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-top: 140px;
use a Use the margin shorthand property  for all sides you are covering.

2023-10-04 09:37 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-top: 50px;
same here

2023-10-04 09:37 UTC, JAPHETHNYARANGA commented on .husky/prepare-commit-msg
> +fi
add this folder to gitignore to avoid pushing these changes

2023-10-04 09:37 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    }
same

2023-10-04 09:37 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    }
same

2023-10-04 12:04 UTC, mshekerotokiti commented
> # Description
> I have created the news page, with the read more links that direct to the specific blog page
> 
> Reference the issue related to this PR as shown below. Every issue has its own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).
> 
> Fixes # 7
> 
> ## Type of change
> ✅ New feature (non-breaking change which adds functionality)
> 
> ## Screenshot (optional)
> ![Screenshot from 2023-10-02 13-28-16](https://user-images.githubusercontent.com/116310361/271946810-9cd3e27e-96c4-4393-aae1-4e40a70f446c.png)
>  
![Screenshot from 2023-10-04 15-03-12](https://github.com/italanta/elewa-website-html/assets/116310361/e69485ee-7a26-4ee2-b0c8-474922991a85)

> ## Checklist
> ✅ My code follows the style guidelines of this project ✅ I have performed a self-review of my code ✅ I have commented my code, particularly in hard-to-understand areas ✅ My changes generate no new warnings

2023-10-26 09:04 UTC, JAPHETHNYARANGA commented
This is good work, the design is nice.Good work. Just closing the pr since the issue is closed

2023-10-26 09:04 UTC, closed without merging