Homepage partners
italanta/elewa-website-html pull request #144
Opened 2023-10-02 20:03 UTC by Pychangeric

# This pull request up holds the work for the partners section where I have added the partners logos has required by the checks.

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #3 (issue#3) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

issue #3 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional) 
![image](https://github.com/italanta/elewa-website-html/assets/126661919/3bf50c3f-7781-4805-bad2-f0acd80ea234)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-03 12:07 UTC, JAPHETHNYARANGA requested changes
Please make the page responsive and send screenshots of web and mobile view

2023-10-03 12:07 UTC, JAPHETHNYARANGA commented on index.html
> +        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUsAAACYCAMAAABatDuZAAAAn1BMVEX////bZSfZWQDaYR/339bZWgfZVwD++vf01sriiF7bYyPZXRLvvqraYBvaXhX78Ovstp/lkWz00cPfeUn4597jimT//Pjgf1Lvwq/noYX
?? why

2023-10-03 12:07 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-top: 30px;
use a single margin property for this

2023-10-03 12:07 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-left: 450px;
this also.  If the margin property has four values:

margin: 25px 50px 75px 100px;
top margin is 25px
right margin is 50px
bottom margin is 75px
left margin is 100px

2023-10-05 07:31 UTC, Pychangeric commented
@JAPHETHNYARANGA   Hello , I have done the collection on the respinsiveness. I ask for Re-review

2023-10-19 09:33 UTC, JAPHETHNYARANGA commented
closing this pr as issue is done already, please pick another issue

2023-10-19 09:33 UTC, closed without merging