Create homepage overview section muya
italanta/elewa-website-html pull request #155
Opened 2023-10-03 10:26 UTC by melmuya

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [#4  ] New feature (non-breaking change which adds functionality)

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ #] My code follows the style guidelines of this project
- [ #] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ #] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-05 06:20 UTC, paulkahura requested changes
This is a nice attempt but attach the images for mobile, desktop and tablet for review. Also in the template to check a box use `[x]` instead of `[#]`

2023-10-05 06:20 UTC, paulkahura commented on src/ts/index.ts
don't create pr with console.logs in your code

2023-10-05 06:20 UTC, paulkahura commented on src/css/style.css
use rem/em over px

2023-10-22 19:44 UTC, JAPHETHNYARANGA commented
Good attempt but this issue has been closed . Please pick another open issue. Hint; don't delete code already in a file when working on it.

2023-10-22 19:44 UTC, closed without merging