✨📝 create contact page html file #70
italanta/elewa-website-html pull request #157
Opened 2023-10-03 11:24 UTC by Schola-droid

# Description

Create Contact Page HTML File

Fixes #81 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
<img width="510" alt="Screenshot 2023-10-03 at 14 22 34" src="https://github.com/italanta/elewa-website-html/assets/126864511/012d90d1-4dec-4dbc-8c19-e5f0b9cafc5a">
@https://github.com/Johnsonnjichi

2023-10-05 06:17 UTC, paulkahura requested changes
Good attempt. check comment

2023-10-05 06:17 UTC, paulkahura commented on index.html
> +
extra space

2023-10-07 10:39 UTC, Schola-droid commented on index.html
> +
> extra space

I've corrected it, Sir.

2023-10-21 12:55 UTC, JAPHETHNYARANGA commented
Good attempt but please pick another isuue. Closing this pr as the issue is done already in another pr.

2023-10-21 12:55 UTC, closed without merging