Homepage partners section - 4
italanta/elewa-website-html pull request #167
Opened 2023-10-03 13:54 UTC by jessemutua

# Description

I added the provided images in HTML and styled them making them responsive for different screen sizes.

Fixes #3

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
![Screenshot from 2023-10-03 16-46-54](https://github.com/italanta/elewa-website-html/assets/84849697/f12b83d5-72d5-4e57-a14a-862c529e171a)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-10-03 13:56 UTC, jessemutua commented
@LemmyMwaura

2023-10-03 14:22 UTC, JAPHETHNYARANGA requested changes
please check the background color codes, and how will the section be used if it is a whole page instead of a section. Media queries are used to make the page responsive, the application may need styles before making the page responsive, i cannot see this. Please address this. Thank you

2023-10-03 14:22 UTC, JAPHETHNYARANGA commented on index.html
> +    <div class="container">
what is the purpose of this welcome

2023-10-03 14:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +        height: 100vh;
it will be a page, not a section , with this property

2023-10-03 17:34 UTC, jessemutua commented
@LemmyMwaura

2023-10-04 02:55 UTC, jessemutua commented
@JAPHETHNYARANGA , i have reviewed and resolved the issues raised

2023-10-04 09:09 UTC, jessemutua commented
@LemmyMwaura , I reviewed the issues raised

2023-10-04 09:13 UTC, jessemutua commented
@LemmyMwaura , I reviewed the issues raised

2023-10-19 09:36 UTC, JAPHETHNYARANGA commented
good work but closing this pr as the issue is done ,please pick another issue. Thank you

2023-10-19 09:36 UTC, closed without merging