Website header
italanta/elewa-website-html pull request #171
Opened 2023-10-03 14:29 UTC by Medrine-Jepkemoi

# Description

I have created the header which includes: 

1. "Elewa" logo on the left
2. A transparent background 
3. Black text in correct font 
4. Contact button on the right

This is issue #1

## Type of change

Please delete options that are not relevant.

-  Bug fix (non-breaking change which fixes an issue)
-  New feature (non-breaking change which adds functionality)

## Screenshot (optional)
<img width="1470" alt="Screenshot 2023-10-03 at 17 20 39" src="https://github.com/italanta/elewa-website-html/assets/99050771/567368c8-ce94-45c5-8d3f-4698809ed6ac">

## Checklist

- My code follows the style guidelines of this project
-  I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
-  My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
-  Any dependent changes have been merged and published in downstream modules

2023-10-05 06:08 UTC, paulkahura requested changes
Nice attempt however I'll need the mobile and tablet screenshots to review.

2023-10-05 06:08 UTC, paulkahura commented on src/css/style.css
use rem/em over px

2023-10-19 06:51 UTC, JAPHETHNYARANGA reviewed
closing as this is done

2023-10-19 07:31 UTC, JAPHETHNYARANGA reviewed
closing as this is already done

2023-10-19 07:31 UTC, closed without merging