Homepage
italanta/elewa-website-html pull request #172
Opened 2023-10-03 15:05 UTC by mumbi58

# Description
"I have created a homepage with minimal changes. The primary motivation was to establish a basic online presence. There are no specific dependencies required for this simple homepage setup."

#2 
## Type of change
- [ ] New feature (non-breaking change which adds functionality)
## Screenshot (optional)
![image](https://github.com/italanta/elewa-website-html/assets/126749794/45838400-9718-4b26-95b0-6e779105d10a)

Ensured proper rendering on various screen sizes by adjusting the browser window width in the inspect tool.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-05 06:06 UTC, paulkahura requested changes
Hello there Kindly include screenshots. Mobile and tablet. Good day!

2023-10-05 06:06 UTC, paulkahura commented on src/css/style.css
> +
remove the spaces

2023-10-05 06:06 UTC, paulkahura commented on src/css/style.css
use rem/em over px

2023-10-05 06:06 UTC, paulkahura commented on src/css/style.css
> +
check the font and the size

2023-10-26 12:43 UTC, JAPHETHNYARANGA commented
Thia is good work, ATleast you are learning. Closing this pr as it is already done

2023-10-26 12:43 UTC, closed without merging