:white_check_mark: Overview section
italanta/elewa-website-html pull request #184
Opened 2023-10-04 07:56 UTC by Bsquiat1

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-05 05:50 UTC, paulkahura requested changes

2023-10-05 05:50 UTC, paulkahura commented on index.html
Add tablet screenshot. Otherwise great job

2023-10-05 06:31 UTC, Bsquiat1 commented on index.html
Thank you. I have added tablet screenshot

2023-10-05 06:47 UTC, paulkahura requested changes
Also use rem/em instead of px. There are online calculators. Also the margin between the text and image is abit off. Otherwise looks good to me.

2023-10-05 07:45 UTC, Bsquiat1 commented on index.html
I have made the changes

2023-10-22 19:45 UTC, JAPHETHNYARANGA commented
Good attempt but this issue has been closed . Please pick another open issue. Hint; don't delete code already in a file when working on it.

2023-10-22 19:45 UTC, closed without merging