🎨 Website header #1
italanta/elewa-website-html pull request #185
Opened 2023-10-04 12:26 UTC by jelizasilatei

# Description

This pull request introduces a new website header/navbar, enhancing the user experience and navigation. 
The header includes a logo, navigation links, an action button, and a responsive dropdown menu for smaller screens. 
It has been meticulously designed and styled to ensure a seamless and visually appealing transition across various screen sizes. 

Fixes #1

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
Desktop:
![Desktop- website header](https://github.com/italanta/elewa-website-html/assets/104438169/63517c4c-465b-4615-9b7e-3e1c9b6dcbf3)

Tablet:
![Tablet(toggle-bars) Website header](https://github.com/italanta/elewa-website-html/assets/104438169/65d44e20-27b7-4496-92e0-a069a52c577e)
![Tablet(dropdown-menu) Website-header](https://github.com/italanta/elewa-website-html/assets/104438169/f4edd18d-b3ca-409e-9fe8-f16d3d6b4e37)

Mobile:
![Mobile(togle-bar) Website header](https://github.com/italanta/elewa-website-html/assets/104438169/89e024c3-0673-4292-bac0-0380cd468817)
![Mobile(dropdown-menu) Website header](https://github.com/italanta/elewa-website-html/assets/104438169/0bee9c98-79fd-4556-87e0-277500ed1534)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-10-04 12:28 UTC, jelizasilatei commented
I worked on this with https://github.com/Lord-Gitonga.
Kindly review my pull request.

2023-10-05 05:46 UTC, paulkahura requested changes

2023-10-05 05:46 UTC, paulkahura commented on src/css/style.css
Great job! One minor change: the font should be the one in the designs.

2023-10-05 07:57 UTC, jelizasilatei commented on src/css/style.css
Thank you,
I have incorporated the fonts required.

2023-10-19 07:44 UTC, closed without merging

2023-10-19 07:44 UTC, JAPHETHNYARANGA commented
closing as this is done, please pick another issue