:memo:docs:Conversational Learning Page HTML file created
italanta/elewa-website-html pull request #186
Opened 2023-10-04 13:15 UTC by Medrine-Jepkemoi

# Description

Creation of the Conversational Learning Page HTML file where I can add the different sections of my conversational learning page.

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

-  My code follows the style guidelines of this project
-  I have performed a self-review of my code
-  I have commented my code, particularly in hard-to-understand areas
-  I have made corresponding changes to the documentation
- My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
-  Any dependent changes have been merged and published in downstream modules

2023-10-05 05:36 UTC, paulkahura commented
Now you just have to add the basic html structure

2023-10-05 05:42 UTC, paulkahura requested changes

2023-10-05 05:42 UTC, paulkahura commented on src/features/pages/conversational-learning-page.html
Add the basic html structure

2023-10-26 12:45 UTC, JAPHETHNYARANGA commented
Thia is good work, ATleast you are learning. Closing this pr as it is already done

2023-10-26 12:45 UTC, closed without merging