:lipstick: :art: Created booklets-page hero section
italanta/elewa-website-html pull request #188
Opened 2023-10-04 17:05 UTC by Sarah-Wambui

# Description

Created booklets-page her section

#73 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings

2023-10-05 05:37 UTC, paulkahura commented
kindly include a screenshot for both mobile and desktop for review

2023-10-05 05:41 UTC, paulkahura requested changes

2023-10-05 05:41 UTC, paulkahura commented on src/css/style.css
Kindly include the screenshot for both mobile and desktop

2023-10-05 07:17 UTC, Sarah-Wambui commented
![Desktop](https://github.com/italanta/elewa-website-html/assets/126576303/2eeb30bf-afbe-4697-8f17-9019d14fe8fb)
![mobile](https://github.com/italanta/elewa-website-html/assets/126576303/4fb7501b-7ca0-4d5d-98d1-404a61423b1a)

2023-10-21 17:04 UTC, JAPHETHNYARANGA commented
Good attempt closing this pr as it is already done, please pick another issue

2023-10-21 17:04 UTC, closed without merging