:sparkles:News #7
italanta/elewa-website-html pull request #272
Opened 2023-10-12 09:04 UTC by SKaranjaN

# Description

Created the new blog page which is  also mobile responsive.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers #7 (https://github.com/italanta/elewa-website-html/issues/7).

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshot
![image](https://github.com/italanta/elewa-website-html/assets/122862095/545367ef-7d12-457a-a253-8c411969d09a)
![image](https://github.com/italanta/elewa-website-html/assets/122862095/52c233e1-3e63-47d5-8bb8-8c1b05bd1c4b)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-10-12 09:30 UTC, JAPHETHNYARANGA requested changes
Very good attempt. Change the pr emoji to a lipstick. Then push only the required files, use shorthand for margin.

2023-10-12 09:30 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +}
use margin shorthand

2023-10-12 09:30 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  transition: 2s;
this doesent take long?

2023-10-12 09:30 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-left: 8px;
shorthand

2023-10-12 09:30 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-right: 10px;
here also

2023-10-12 09:30 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-left: 8px;
here

2023-10-12 09:30 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-top: -50px;
here

2023-10-12 09:30 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-top: 40px
here

2023-10-12 10:04 UTC, SKaranjaN commented on src/css/style.css
> +  margin-left: 8px;
I have made the requested changes.

2023-10-26 09:03 UTC, JAPHETHNYARANGA commented
This is good work, the design is nice.Good work. Just closing the pr since the issue is closed

2023-10-26 09:03 UTC, closed without merging