:zap: News section
italanta/elewa-website-html pull request #273
Opened 2023-10-12 09:09 UTC by Sharoun-Madoya

# Description
Create Home Page News Section Component #7

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [#7 ](https://github.com/italanta/elewa-website-html/issues/7).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-10-12 09:22 UTC, JAPHETHNYARANGA requested changes
Good attempt, edit pr name to have the issue number, change emji to a lipstick. And push only the required files. Don't forget to attach screenshots. Thank you.

2023-10-12 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> + margin-left: 80px;
use shorthand

2023-10-12 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-left: 30px;
here also, for the margin

2023-10-12 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-left: 10%;
here

2023-10-12 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-left: 15%;
here

2023-10-12 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    margin-left: 50px;
here

2023-10-12 10:08 UTC, Sharoun-Madoya commented on src/css/style.css
> +    margin-left: 50px;
Done the Changes

2023-10-13 08:08 UTC, Sharoun-Madoya commented
> # Description
> Create Home Page News Section Component #7
> 
> Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [#7 ](https://github.com/italanta/elewa-website-html/issues/7).
> 
> Fixes # (issue) - _Example_: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.
> Screen Shot
![101](https://github.com/italanta/elewa-website-html/assets/126710481/917d4357-77d5-447b-9839-727a4f885d48)
![102](https://github.com/italanta/elewa-website-html/assets/126710481/6b30bd2a-8202-486c-85dd-0cec226b1a9d)


> ## Type of change
> Please delete options that are not relevant.
> 
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  This change requires a documentation update
> 
> ## Checklist
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my code
> * [x]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings

2023-10-26 09:02 UTC, JAPHETHNYARANGA commented
This is good work, the design is nice.Good work. Just closing the pr since the issue is closed

2023-10-26 09:02 UTC, closed without merging