✨📝Feat: Created Home Page News Section Structure
italanta/elewa-website-html pull request #54
Opened 2023-09-28 11:22 UTC by manotim

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #7 

## Type of change
## Created Home Page for News Section

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
file:///home/manoti/Pictures/Screenshots/Screenshot%20from%202023-10-03%2013-22-28.png

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-10-03 08:31 UTC, JAPHETHNYARANGA requested changes
please attach screenshots of web and mobile views

2023-10-03 08:31 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +}
use a single margin property  example margin: 10px 10px; specifies margin top and bottom as 10px and right and left as 10px,

2023-10-03 08:31 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-top: 50px;
use single margin

2023-10-03 08:31 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-right: 100px;
same here

2023-10-03 10:55 UTC, manotim commented
![Screenshot from 2023-10-03 13-22-28](https://github.com/italanta/elewa-website-html/assets/52492406/ca62bf2f-f2ae-446c-bc52-1a7f53c50966)
![Screenshot from 2023-10-03 13-31-47](https://github.com/italanta/elewa-website-html/assets/52492406/a78170d4-8e61-46cb-b25a-1b8788f750c2)

2023-10-03 11:05 UTC, manotim commented on src/css/style.css
> +  margin-top: 50px;
Done

2023-10-03 11:05 UTC, manotim commented on src/css/style.css
> +  margin-right: 100px;
Done

2023-10-03 11:06 UTC, manotim commented
Screenshots for web and mobile view now attached.

2023-10-03 11:08 UTC, manotim commented
Done. Kindly, Review.

On Tue, 3 Oct 2023 at 11:32, Japheth Nyaranga ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> please attach screenshots of web and mobile views
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/54#discussion_r1343713613>
> :
>
> > +  color: #202020;
> +  margin-left: 120px;
> +  margin-bottom: 100px;
> +}
>
> use a single margin property example margin: 10px 10px; specifies margin
> top and bottom as 10px and right and left as 10px,
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/54#discussion_r1343715173>
> :
>
> > +  margin-left: 110px;
> +  margin-right: 100px;
> +  margin-top: 50px;
>
> use single margin
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/54#discussion_r1343715376>
> :
>
> > +  margin-top: 140px;
> +  margin-left: 50px;
> +  margin-right: 100px;
>
> same here
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website-html/pull/54#pullrequestreview-1654638552>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQPQ5WXGYDMFYI6E5MIQRLX5PEQVAVCNFSM6AAAAAA5KZRQQ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJUGYZTQNJVGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-26 12:22 UTC, JAPHETHNYARANGA commented
Thia is good work, ATleast you are learning. Closing this pr as it is already done

2023-10-26 12:22 UTC, closed without merging