🎉;feat:home page overview
italanta/elewa-website-html pull request #62
Opened 2023-09-28 13:01 UTC by Max-Mahinda

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)
![Screenshot from 2023-09-28 15-57-46](https://github.com/italanta/elewa-website-html/assets/126717860/cd200698-5497-4d3c-970b-66d9bb1d1883)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-03 09:22 UTC, JAPHETHNYARANGA requested changes
please go through your files again and optimize it

2023-10-03 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +
unnecessary space

2023-10-03 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +}
declare parents elements at the top

2023-10-03 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +  margin-bottom: 20%;
use a single margin property i.e margin:10 10 10 10;

2023-10-03 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +    }
there is repetition here, be keen

2023-10-03 09:22 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +}
since this is the smallest device width, i recommend it goes to the bottom of other larger device widths

2023-10-06 08:30 UTC, Max-Mahinda commented
Done

On Tue, 3 Oct 2023 at 12:22, Japheth Nyaranga ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> please go through your files again and optimize it
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343783303>
> :
>
> > +
> +
> +
> +
> +
> +
>
> unnecessary space
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343784324>
> :
>
> > +body{
> +  background-color: #DBC2F5;
> +}
>
> declare parents elements at the top
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343785155>
> :
>
> > +  margin-top: 15%;
> +  margin-left: 20%;
> +  margin-bottom: 20%;
>
> use a single margin property i.e margin:10 10 10 10;
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343787072>
> :
>
> > +/* For Mobile Landscape View */
> ***@***.*** screen and (max-device-width: 640px)
> +    and (orientation: landscape) {
> +    .gfg-div {
> +        width: 400px;
> +        height: 200px;
> +        background-color: cyan;
> +        color: black;
> +    }
> +}
> +
> +/* For Mobile Phones Portrait or Landscape View */
> ***@***.*** screen
> +    and (max-device-width: 640px) {
> +    .gfg-div {
> +        width: 400px;
> +        height: 200px;
> +        background-color: chartreuse;
> +        color: black;
> +    }
>
> there is repetition here, be keen
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343788787>
> :
>
> > ***@***.*** screen and (max-device-width: 480px)
> +    and (orientation: portrait) {
> +    .gfg-div {
> +        width: 200px;
> +        height: 200px;
> +        background-color: red;
> +        color: #fff;
> +    }
> +}
>
> since this is the smallest device width, i recommend it goes to the bottom
> of other larger device widths
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website-html/pull/62#pullrequestreview-1654740012>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6GY7JGZUIC32RBR6F3EVJTX5PKM5AVCNFSM6AAAAAA5K5YLHWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJUG42DAMBRGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-16 15:52 UTC, Max-Mahinda commented
Dear sir,
Submitted few projects but haven’t gotten any response yet from you guys.

Regards,
Max Mwangi.
On Tue, 3 Oct 2023 at 12:22, Japheth Nyaranga ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> please go through your files again and optimize it
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343783303>
> :
>
> > +
> +
> +
> +
> +
> +
>
> unnecessary space
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343784324>
> :
>
> > +body{
> +  background-color: #DBC2F5;
> +}
>
> declare parents elements at the top
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343785155>
> :
>
> > +  margin-top: 15%;
> +  margin-left: 20%;
> +  margin-bottom: 20%;
>
> use a single margin property i.e margin:10 10 10 10;
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343787072>
> :
>
> > +/* For Mobile Landscape View */
> ***@***.*** screen and (max-device-width: 640px)
> +    and (orientation: landscape) {
> +    .gfg-div {
> +        width: 400px;
> +        height: 200px;
> +        background-color: cyan;
> +        color: black;
> +    }
> +}
> +
> +/* For Mobile Phones Portrait or Landscape View */
> ***@***.*** screen
> +    and (max-device-width: 640px) {
> +    .gfg-div {
> +        width: 400px;
> +        height: 200px;
> +        background-color: chartreuse;
> +        color: black;
> +    }
>
> there is repetition here, be keen
> ------------------------------
>
> In src/css/style.css
> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343788787>
> :
>
> > ***@***.*** screen and (max-device-width: 480px)
> +    and (orientation: portrait) {
> +    .gfg-div {
> +        width: 200px;
> +        height: 200px;
> +        background-color: red;
> +        color: #fff;
> +    }
> +}
>
> since this is the smallest device width, i recommend it goes to the bottom
> of other larger device widths
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website-html/pull/62#pullrequestreview-1654740012>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6GY7JGZUIC32RBR6F3EVJTX5PKM5AVCNFSM6AAAAAA5K5YLHWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJUG42DAMBRGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-18 08:35 UTC, Max-Mahinda commented
Heey i have also submitted so many but cant see them in the merging list? I
dont understand why

On Mon, 16 Oct 2023 at 18:51, Max Mwangi mahinda ***@***.***>
wrote:

>
>  Dear sir,
> Submitted few projects but haven’t gotten any response yet from you guys.
>
> Regards,
> Max Mwangi.
> On Tue, 3 Oct 2023 at 12:22, Japheth Nyaranga ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> please go through your files again and optimize it
>> ------------------------------
>>
>> In src/css/style.css
>> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343783303>
>> :
>>
>> > +
>> +
>> +
>> +
>> +
>> +
>>
>> unnecessary space
>> ------------------------------
>>
>> In src/css/style.css
>> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343784324>
>> :
>>
>> > +body{
>> +  background-color: #DBC2F5;
>> +}
>>
>> declare parents elements at the top
>> ------------------------------
>>
>> In src/css/style.css
>> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343785155>
>> :
>>
>> > +  margin-top: 15%;
>> +  margin-left: 20%;
>> +  margin-bottom: 20%;
>>
>> use a single margin property i.e margin:10 10 10 10;
>> ------------------------------
>>
>> In src/css/style.css
>> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343787072>
>> :
>>
>> > +/* For Mobile Landscape View */
>> ***@***.*** screen and (max-device-width: 640px)
>> +    and (orientation: landscape) {
>> +    .gfg-div {
>> +        width: 400px;
>> +        height: 200px;
>> +        background-color: cyan;
>> +        color: black;
>> +    }
>> +}
>> +
>> +/* For Mobile Phones Portrait or Landscape View */
>> ***@***.*** screen
>> +    and (max-device-width: 640px) {
>> +    .gfg-div {
>> +        width: 400px;
>> +        height: 200px;
>> +        background-color: chartreuse;
>> +        color: black;
>> +    }
>>
>> there is repetition here, be keen
>> ------------------------------
>>
>> In src/css/style.css
>> <https://github.com/italanta/elewa-website-html/pull/62#discussion_r1343788787>
>> :
>>
>> > ***@***.*** screen and (max-device-width: 480px)
>> +    and (orientation: portrait) {
>> +    .gfg-div {
>> +        width: 200px;
>> +        height: 200px;
>> +        background-color: red;
>> +        color: #fff;
>> +    }
>> +}
>>
>> since this is the smallest device width, i recommend it goes to the
>> bottom of other larger device widths
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/italanta/elewa-website-html/pull/62#pullrequestreview-1654740012>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A6GY7JGZUIC32RBR6F3EVJTX5PKM5AVCNFSM6AAAAAA5K5YLHWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJUG42DAMBRGI>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-10-22 19:42 UTC, JAPHETHNYARANGA commented
Good attempt but this issue has been closed . Please pick another open issue. Hint; don't delete code already in a file when working on it.

2023-10-22 19:42 UTC, closed without merging