🎉  Starting the home page overview #4
italanta/elewa-website-html pull request #68
Opened 2023-09-29 06:49 UTC by jelizasilatei

# Description

Build an overview container.
Worked on this issue with Victor.

Fixes #4

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code

2023-09-29 19:10 UTC, jelizasilatei commented
Kindly review my pull request, I worked on this with Victor and this is his github account https://github.com/Vickynjoroge.

2023-10-03 10:08 UTC, JAPHETHNYARANGA requested changes
Please provide web and mobile screenshot of the page

2023-10-03 10:08 UTC, JAPHETHNYARANGA commented on index.html
> +      <img id="overview-image" src="src/assests/gettyimages-98473330-2048x2048@2x.png" alt="Your Image">
provide better alternative name

2023-10-03 10:08 UTC, JAPHETHNYARANGA commented on src/css/style.css
> +}
if the width of th image div is 100% , where are the other text elements that need to be beside the image placed

2023-10-03 10:08 UTC, JAPHETHNYARANGA commented on src/ts/index.ts
> +console.log ('hi');
edit only required files

2023-10-04 06:09 UTC, jelizasilatei commented
Screenshots for Web and Mobile pae
Web:
![Web screenshot for home page overview section](https://github.com/italanta/elewa-website-html/assets/104438169/0753a4e4-4815-4ba3-b9be-7e89c0b900c8)

Mobile:
![Mobile screenshot for home page overview section](https://github.com/italanta/elewa-website-html/assets/104438169/267ba395-42fe-4df5-865b-2820cfec6bd6)

2023-10-04 06:38 UTC, jelizasilatei commented on index.html
> +      <img id="overview-image" src="src/assests/gettyimages-98473330-2048x2048@2x.png" alt="Your Image">
`  <!-- Home Page Overview Container -->
  <div class="homepage-overview-container">
    <!-- Home page Overview Image Section -->
    <div class="homepage-overview-image">
      <img id="overview-image" src="src/assests/gettyimages-98473330-2048x2048@2x.png" alt="Your Image">
    </div>`

2023-10-04 06:44 UTC, jelizasilatei commented on src/css/style.css
> +}
I used a Mobile-First Responsive Design the mobile and tablet page has a width of 100% which mean the image and text elements will be vertically arrange.
The text image comes below the image.
When it is on a desktop screen the image floats to the left and text elements float to the right

2023-10-04 06:45 UTC, jelizasilatei commented on src/ts/index.ts
> +console.log ('hi');
I have deleted this line of code.

2023-10-04 07:45 UTC, JAPHETHNYARANGA approved these changes

2023-10-22 19:26 UTC, JAPHETHNYARANGA commented
Good work, but next time dont delete code already in the specific file you are editing

2023-10-22 19:26 UTC, closed without merging

2023-10-24 11:20 UTC, jelizasilatei commented
Okay


On Sun, Oct 22, 2023 at 10:27 PM Japheth Nyaranga ***@***.***>
wrote:

> Good work, but next time dont delete code already in the specific file you
> are editing
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website-html/pull/68#issuecomment-1774178380>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY4ZTGJGSZ24APYYICTF7QTYAVXQJAVCNFSM6AAAAAA5MANAZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZUGE3TQMZYGA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>