🎨 Create Home Page Overview Section
italanta/elewa-website-html pull request #83
Opened 2023-09-29 10:43 UTC by MarsMwau

# Description

I have created and styled the overview section to meet the required design.

Reference the issue related to this PR as shown below. Every issue has its own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ *] New feature (non-breaking change which adds functionality)
- [* ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)
<img width="942" alt="Screenshot 2023-09-29 133942" src="https://github.com/italanta/elewa-website-html/assets/115712038/59c80dcd-3f7f-4b68-9ea5-4a7706d56094">

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [* ] My code follows the style guidelines of this project
- [* ] I have performed a self-review of my code
- [ *] I have commented my code, particularly in hard-to-understand areas
- [* ] I have made corresponding changes to the documentation
- [ *] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-04 12:11 UTC, JAPHETHNYARANGA requested changes
please review you code , theres a horizontal scroll bar , so check on your box model styles , and please attach screenshot of mobile, thanks.

2023-10-04 12:11 UTC, JAPHETHNYARANGA commented on index.html
> +        <br />
use box model to space

2023-10-04 12:11 UTC, JAPHETHNYARANGA commented on index.html
> +        <br />
use box model to space

2023-10-20 12:11 UTC, MarsMwau commented on index.html
> +        <br />
complete

2023-10-22 19:43 UTC, JAPHETHNYARANGA commented
Good attempt but this issue has been closed . Please pick another open issue. Hint; don't delete code already in a file when working on it.

2023-10-22 19:43 UTC, closed without merging